### ISSUE TITLE
iss claim does not contain https in url causing backend to reject auth token

### ISSUE THREAD

**Issue by javiersvg** [google/google-api-javascript-client#512]
## The issue:
I am working to create a front end with this library and a back end with spring scurity 5.
Wen the jwt token is veing validated after being generated with the java script library the back end responds me with an error as follows:
**[invalid_request] This iss claim is not equal to the configured issuer**
After debuging I found that this is due to the claim.iss element in the jwt tocken comming as:

``` json
{
"iss":"accounts.google.com",
"azp":"...",
"aud":"...",
"sub":"...",
"email":"...@gmail.com",
"email_verified":true,
"at_hash":"...",
"name":"...",
"picture":"...",
"given_name":"...",
"family_name":"...",
"locale":"...",
"iat":...,
"exp":...,
"jti":"..."}
```
While spring expects the iss to start with "https://..."
While testing with the [google jwt playground](https://developers.google.com/oauthplayground/) the tokens where generated with the proper iss:
```json
{
"iss":"https://accounts.google.com",
"azp":"...",
"aud":"...",
"sub":"...",
"email":"...@gmail.com",
"email_verified":true,
"at_hash":"...",
"name":"...",
"picture":"...",
"given_name":"...",
"family_name":"...",
"locale":"...",
"iat":...,
"exp":...}
```
The only other difference I see between the 2 tokens is that the one from the library has the jti field wihich the jwt playground one does not.

## The question
**Could you help me understand if I should adapt the backend to which issuer value?**
* https://accounts.google.com
* accounts.google.com

## My configuration:

I am configuring the library with the following entry in my index.html:
```html
<script src="https://apis.google.com/js/api.js"></script>
```
and I am using angular 6 to call the following method to obtain my token:
```typescript
signInGoogle(): Observable<Profile> {
    const auth2 = gapi.auth2.getAuthInstance();
    return fromPromise(auth2.signIn()).pipe(
      mergeMap((resp: gapi.auth2.GoogleUser)  => {
        return this.signInBackEnd(resp.getAuthResponse());
      })
    );
  }

  private signInBackEnd(response: gapi.auth2.AuthResponse): Observable<Profile> {

    const headers = new HttpHeaders().append('Authorization', 'Bearer ' + response.id_token)
    return this.http.get<Profile>(this.signinUrl, {headers: headers}).pipe(
      mergeMap<any, Profile>(_ => this.http.get<Profile>('/api/user')),
      tap(_ => this.log(`singin success`)),
      catchError(this.handleError<Profile>('signin'))
    );
  }
```

In the back end I am using spring security 5 resource server based on spring boot plug in 2.1.2 with the following configuration:

```yaml
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ....apps.googleusercontent.com
            client-secret: ...
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
```
I am working to remove the "https://" part but spring does not like it that much hence I am trying to understand if this is the correct thing to do.

**Comment by javiersvg** [comment]
I found no way to change this on the client side and the back end (Spring) only worked after removing the validator that took the full url for validation. 
I achieved this by changing the configuration to:
```yaml
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
         jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
```

Hope it helps some one.
